[github/actions/composer] Verify that symfony.lock is up-to-date

diff --git a/.github/workflows/php_check.yml b/.github/workflows/php_check.yml
--- a/.github/workflows/php_check.yml
+++ b/.github/workflows/php_check.yml
@@ -73,3 +73,12 @@ jobs:
           commit_user_email: "wayfapper-bot@users.noreply.github.com"
           commit_user_name: "Wayfapper-Bot"
           file_pattern: "symfony.lock"
+
+      - name: "Verify that symfony.lock is up-to-date"
+        if: "github.actor != 'dependabot[bot]'"
+        run: |
+          diff=$(git diff symfony.lock)
+          if [[ "${diff}" != "" ]]; then
+            echo "::error file=symfony.lock::symfony.lock is not up-to-date."
+            exit 1
+          fi
